### ISSUE TITLE
Click event

### ISSUE THREAD

**Issue by winster** [andrewn/raspi-rotary-encoder#1]
Hello,

Will it handle click event? It works perfectly with forward and backward rotation.

Click  -> Press down

**Comment by andrewn** [comment]
Hi @winster. At the moment there's only support for detecting rotation.

I usually use [Johnny-Five's `Button` class](http://johnny-five.io/api/button/) to handle the Rotary Encoder's button in my projects.

I don't think it makes sense in duplicating that functionality in this project as Johnny-Five's `Button` has lots of useful features.

**Comment by andrewn** [comment]
Closing this as the functionality can be achieved using Johnny-Five.
